package mihon.entry.interactions.documentation.rendering

import mihon.entry.interactions.documentation.source.EntrySourceSdkConsumerCoveragePlan

const val ENTRY_SOURCE_SDK_COVERAGE_START_MARKER =
    "<!-- BEGIN GENERATED SOURCE SDK CONSUMER COVERAGE -->"
const val ENTRY_SOURCE_SDK_COVERAGE_END_MARKER =
    "<!-- END GENERATED SOURCE SDK CONSUMER COVERAGE -->"

fun renderEntrySourceSdkConsumerCoverageMarkdown(plan: EntrySourceSdkConsumerCoveragePlan): String {
    require(plan.isComplete) {
        buildString {
            appendLine("Cannot render incomplete source SDK consumer coverage:")
            plan.issues.forEach { issue ->
                append("- ")
                append(issue.responsibleOwner.value)
                append(": ")
                appendLine(issue.details)
            }
        }.trimEnd()
    }

    return buildString {
        appendLine("<!-- Generated by ./gradlew generateSourceSdkConsumerCoverage. Do not edit this region. -->")
        appendLine()
        appendLine("| SDK contract | Feature | Contextual integration | Evidence input |")
        appendLine("| --- | --- | --- | --- |")
        plan.consumers.forEach { consumer ->
            append("| `")
            append(requireNotNull(consumer.contract.simpleName))
            append("` | `")
            append(consumer.feature.value)
            append("` | `")
            append(consumer.integration.value)
            append("` | `")
            append(consumer.contextInput.value)
            appendLine("` |")
        }
    }.trimEnd()
}

fun replaceEntrySourceSdkConsumerCoverageGeneratedRegion(
    document: String,
    generatedMarkdown: String,
): String = replaceGeneratedMarkdownRegion(
    document = document,
    generatedMarkdown = generatedMarkdown,
    startMarker = ENTRY_SOURCE_SDK_COVERAGE_START_MARKER,
    endMarker = ENTRY_SOURCE_SDK_COVERAGE_END_MARKER,
)

fun undocumentedEntrySourceSdkContracts(
    document: String,
    plan: EntrySourceSdkConsumerCoveragePlan,
): List<String> {
    val handwrittenDocumentation = removeGeneratedMarkdownRegion(
        document = document,
        startMarker = ENTRY_SOURCE_SDK_COVERAGE_START_MARKER,
        endMarker = ENTRY_SOURCE_SDK_COVERAGE_END_MARKER,
    )
    return plan.consumers
        .map { requireNotNull(it.contract.simpleName) }
        .distinct()
        .filterNot { contract -> "`$contract`" in handwrittenDocumentation }
        .sorted()
}
