package mihon.entry.interactions.documentation.rendering

import mihon.entry.interactions.documentation.EntryContentTypeReferenceSection
import mihon.entry.interactions.documentation.EntryContentTypeReferenceStatus
import mihon.entry.interactions.documentation.projection.EntryContentTypeReferencePlan
import mihon.feature.graph.ContentTypeId

const val ENTRY_CONTENT_TYPE_REFERENCE_START_MARKER =
    "<!-- BEGIN GENERATED CONTENT TYPE SUPPORT -->"
const val ENTRY_CONTENT_TYPE_REFERENCE_END_MARKER =
    "<!-- END GENERATED CONTENT TYPE SUPPORT -->"

fun renderEntryContentTypeReferenceMarkdown(plan: EntryContentTypeReferencePlan): String {
    require(plan.isComplete) {
        buildString {
            appendLine("Cannot render an incomplete content-type reference plan:")
            plan.issues.forEach { issue ->
                append("- ")
                append(issue.responsibleOwner.value)
                append(": ")
                appendLine(issue.details)
            }
        }.trimEnd()
    }

    val contentTypes = plan.contentTypes.distinct().sortedBy(ContentTypeId::value)
    val rowsBySection = plan.rows.groupBy { it.definition.section }
    val notesBySection = plan.notes.groupBy { it.definition.section }

    return buildString {
        appendLine("<!-- Generated by ./gradlew generateContentTypeReference. Do not edit this region. -->")
        EntryContentTypeReferenceSection.entries
            .sortedBy(EntryContentTypeReferenceSection::order)
            .forEach { section ->
                val rows = rowsBySection[section].orEmpty()
                    .sortedWith(compareBy({ it.definition.order }, { it.definition.id }))
                val notes = notesBySection[section].orEmpty()
                    .sortedWith(compareBy({ it.definition.order }, { it.definition.id }))
                if (rows.isEmpty() && notes.isEmpty()) return@forEach

                appendLine()
                appendLine("## ${section.title}")
                if (rows.isNotEmpty()) {
                    appendLine()
                    append("| Capability |")
                    contentTypes.forEach { contentType -> append(" ${contentType.displayName()} |") }
                    appendLine()
                    append("| --- |")
                    contentTypes.forEach { _ -> append(" :---: |") }
                    appendLine()
                    rows.forEach { row ->
                        append("| ")
                        append(row.definition.label.escapeMarkdownTableCell())
                        append(" |")
                        contentTypes.forEach { contentType ->
                            append(" ")
                            append(row.statuses[contentType].symbol())
                            append(" |")
                        }
                        appendLine()
                    }
                }
                if (notes.isNotEmpty()) {
                    appendLine()
                    appendLine("::: info")
                    appendLine()
                    notes.forEachIndexed { index, note ->
                        if (index > 0) appendLine()
                        appendLine(note.definition.text)
                    }
                    appendLine()
                    appendLine(":::")
                }
            }
    }.trimEnd()
}

fun replaceEntryContentTypeReferenceGeneratedRegion(
    document: String,
    generatedMarkdown: String,
): String = replaceGeneratedMarkdownRegion(
    document = document,
    generatedMarkdown = generatedMarkdown,
    startMarker = ENTRY_CONTENT_TYPE_REFERENCE_START_MARKER,
    endMarker = ENTRY_CONTENT_TYPE_REFERENCE_END_MARKER,
)

private fun ContentTypeId.displayName(): String {
    return value
        .split(Regex("[-_.]+"))
        .joinToString(" ") { part -> part.replaceFirstChar(Char::titlecase) }
}

private fun String.escapeMarkdownTableCell(): String =
    replace("|", "\\|").replace("\r", " ").replace("\n", " ")

private fun EntryContentTypeReferenceStatus?.symbol(): String = when (this) {
    EntryContentTypeReferenceStatus.SUPPORTED -> "✓"
    EntryContentTypeReferenceStatus.SOURCE_DEPENDENT -> "◇"
    null -> "—"
}
