package mihon.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.util.Properties

@CacheableTask
abstract class GenerateApplicationFeatureTopologyTask : DefaultTask() {

    @get:Input
    abstract val variantName: org.gradle.api.provider.Property<String>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val moduleDescriptors: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val source = generateApplicationFeatureProductionTopology(
            variantName = variantName.get(),
            modules = moduleDescriptors.files.map(::applicationFeatureModuleDescriptor),
        )
        val packageDirectory = outputDirectory.get().asFile.resolve("mihon/feature/runtime")
        packageDirectory.mkdirs()
        packageDirectory.resolve("GeneratedApplicationFeatureProductionTopology.kt").writeText(source)
    }
}

internal data class ApplicationFeatureModuleDescriptor(
    val id: String,
    val moduleSymbol: String,
    val source: String,
)

internal fun generateApplicationFeatureProductionTopology(
    variantName: String,
    modules: List<ApplicationFeatureModuleDescriptor>,
): String {
    validateApplicationFeatureDescriptors(modules)
    return buildString {
        appendLine("package mihon.feature.runtime")
        appendLine()
        appendLine("// Generated from owner-local application Feature descriptors for variant $variantName.")
        appendLine("// Do not edit this file or introduce a manually curated production topology.")
        appendLine(
            "internal fun productionApplicationFeatureRuntimeModules(): " +
                "List<ApplicationFeatureRuntimeModule> = listOf(",
        )
        modules.sortedBy(ApplicationFeatureModuleDescriptor::id).forEach { descriptor ->
            appendLine("    registeredApplicationFeatureRuntimeModule(")
            appendLine("        expectedId = \"${descriptor.id}\",")
            appendLine("        module = ${descriptor.moduleSymbol},")
            appendLine("    ),")
        }
        appendLine(")")
        appendLine()
        appendLine("private fun registeredApplicationFeatureRuntimeModule(")
        appendLine("    expectedId: String,")
        appendLine("    module: ApplicationFeatureRuntimeModule,")
        appendLine("): ApplicationFeatureRuntimeModule {")
        appendLine("    check(module.id == expectedId) {")
        appendLine("        \"Generated Application Feature registration \$expectedId resolved module \${module.id}\"")
        appendLine("    }")
        appendLine("    return module")
        appendLine("}")
    }
}

private fun validateApplicationFeatureDescriptors(
    descriptors: List<ApplicationFeatureModuleDescriptor>,
) {
    descriptors.forEach { descriptor ->
        if (!APPLICATION_FEATURE_MODULE_ID.matches(descriptor.id)) {
            throw GradleException(
                "Application Feature descriptor ${descriptor.source} has invalid id '${descriptor.id}'",
            )
        }
        if (!APPLICATION_FEATURE_MODULE_SYMBOL.matches(descriptor.moduleSymbol)) {
            throw GradleException(
                "Application Feature descriptor ${descriptor.source} has invalid symbol '${descriptor.moduleSymbol}'",
            )
        }
    }
    descriptors.groupBy(ApplicationFeatureModuleDescriptor::id)
        .filterValues { it.size > 1 }
        .forEach { (id, duplicates) ->
            throw GradleException(
                "Duplicate Application Feature descriptor id '$id': " +
                    duplicates.map(ApplicationFeatureModuleDescriptor::source).sorted(),
            )
        }
    descriptors.groupBy(ApplicationFeatureModuleDescriptor::moduleSymbol)
        .filterValues { it.size > 1 }
        .forEach { (symbol, duplicates) ->
            throw GradleException(
                "Duplicate Application Feature descriptor symbol '$symbol': " +
                    duplicates.map(ApplicationFeatureModuleDescriptor::source).sorted(),
            )
        }
}

private fun applicationFeatureModuleDescriptor(file: File): ApplicationFeatureModuleDescriptor {
    val properties = Properties().also { values -> file.inputStream().use(values::load) }
    val unknownKeys = properties.stringPropertyNames() - APPLICATION_FEATURE_DESCRIPTOR_KEYS
    if (unknownKeys.isNotEmpty()) {
        throw GradleException("Unknown descriptor keys in ${file.invariantSeparatorsPath}: ${unknownKeys.sorted()}")
    }
    return ApplicationFeatureModuleDescriptor(
        id = properties.requiredApplicationFeatureValue("id", file),
        moduleSymbol = properties.requiredApplicationFeatureValue("module", file),
        source = file.invariantSeparatorsPath,
    )
}

private fun Properties.requiredApplicationFeatureValue(
    key: String,
    file: File,
): String {
    return getProperty(key)?.trim()?.takeIf(String::isNotEmpty)
        ?: throw GradleException("Missing '$key' in ${file.invariantSeparatorsPath}")
}

private val APPLICATION_FEATURE_DESCRIPTOR_KEYS = setOf("id", "module")
private val APPLICATION_FEATURE_MODULE_ID = Regex("""[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*""")
private val APPLICATION_FEATURE_MODULE_SYMBOL =
    Regex("""[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)+""")
