package mihon.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.util.Properties

@CacheableTask
abstract class GenerateEntryInteractionTopologyTask : DefaultTask() {

    @get:Input
    abstract val variantName: org.gradle.api.provider.Property<String>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val featureModuleDescriptors: ConfigurableFileCollection

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val typeModuleDescriptors: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val featureModules = featureModuleDescriptors.files.map(::featureModuleDescriptor)
        val typeModules = typeModuleDescriptors.files.map(::typeModuleDescriptor)
        val source = generateEntryInteractionProductionTopology(
            variantName = variantName.get(),
            featureModules = featureModules,
            typeModules = typeModules,
        )
        val packageDirectory = outputDirectory.get().asFile.resolve("mihon/entry/interactions")
        packageDirectory.mkdirs()
        packageDirectory.resolve("GeneratedEntryInteractionProductionTopology.kt").writeText(source)
    }
}

internal data class EntryFeatureModuleDescriptor(
    val id: String,
    val moduleSymbol: String,
    val source: String,
)

internal data class EntryTypeModuleDescriptor(
    val id: String,
    val factorySymbol: String,
    val source: String,
)

internal fun generateEntryInteractionProductionTopology(
    variantName: String,
    featureModules: List<EntryFeatureModuleDescriptor>,
    typeModules: List<EntryTypeModuleDescriptor>,
): String {
    validateDescriptors("Entry Feature", featureModules.map { DescriptorIdentity(it.id, it.moduleSymbol, it.source) })
    validateDescriptors("Entry type", typeModules.map { DescriptorIdentity(it.id, it.factorySymbol, it.source) })
    if (featureModules.isEmpty()) throw GradleException("No Entry Feature runtime-module descriptors for $variantName")
    if (typeModules.isEmpty()) throw GradleException("No Entry type runtime-module descriptors for $variantName")

    return buildString {
        appendLine("package mihon.entry.interactions")
        appendLine()
        appendLine("import tachiyomi.core.common.preference.ProfilePreferenceOwnerInstaller")
        appendLine()
        appendLine("// Generated from owner-local runtime-module descriptors for variant $variantName.")
        appendLine("// Do not edit this file or introduce a manually curated production topology.")
        appendLine("internal fun productionEntryFeatureRuntimeModules(): List<EntryFeatureRuntimeModule> = listOf(")
        featureModules.sortedBy(EntryFeatureModuleDescriptor::id).forEach { descriptor ->
            appendLine("    registeredEntryFeatureRuntimeModule(")
            appendLine("        expectedId = \"${descriptor.id}\",")
            appendLine("        module = ${descriptor.moduleSymbol},")
            appendLine("    ),")
        }
        appendLine(")")
        appendLine()
        appendLine("internal fun productionEntryTypeRuntimeModules(")
        appendLine("    profilePreferenceOwners: ProfilePreferenceOwnerInstaller,")
        appendLine("): List<EntryTypeRuntimeModule> = listOf(")
        typeModules.sortedBy(EntryTypeModuleDescriptor::id).forEach { descriptor ->
            appendLine("    registeredEntryTypeRuntimeModule(")
            appendLine("        expectedId = \"${descriptor.id}\",")
            appendLine("        module = ${descriptor.factorySymbol}(profilePreferenceOwners),")
            appendLine("    ),")
        }
        appendLine(")")
        appendLine()
        appendLine("private fun registeredEntryFeatureRuntimeModule(")
        appendLine("    expectedId: String,")
        appendLine("    module: EntryFeatureRuntimeModule,")
        appendLine("): EntryFeatureRuntimeModule {")
        appendLine("    check(module.id == expectedId) {")
        appendLine("        \"Generated Entry Feature registration \$expectedId resolved module \${module.id}\"")
        appendLine("    }")
        appendLine("    return module")
        appendLine("}")
        appendLine()
        appendLine("private fun registeredEntryTypeRuntimeModule(")
        appendLine("    expectedId: String,")
        appendLine("    module: EntryTypeRuntimeModule,")
        appendLine("): EntryTypeRuntimeModule {")
        appendLine("    check(module.type.name.equals(expectedId, ignoreCase = true)) {")
        appendLine("        \"Generated Entry type registration \$expectedId resolved module \${module.type}\"")
        appendLine("    }")
        appendLine("    return module")
        appendLine("}")
    }
}

private data class DescriptorIdentity(
    val id: String,
    val symbol: String,
    val source: String,
)

private fun validateDescriptors(label: String, descriptors: List<DescriptorIdentity>) {
    descriptors.forEach { descriptor ->
        if (!MODULE_ID.matches(descriptor.id)) {
            throw GradleException("$label descriptor ${descriptor.source} has invalid id '${descriptor.id}'")
        }
        if (!QUALIFIED_SYMBOL.matches(descriptor.symbol)) {
            throw GradleException(
                "$label descriptor ${descriptor.source} has invalid symbol '${descriptor.symbol}'",
            )
        }
    }
    descriptors.groupBy(DescriptorIdentity::id).filterValues { it.size > 1 }.forEach { (id, duplicates) ->
        throw GradleException(
            "Duplicate $label descriptor id '$id': ${duplicates.map(DescriptorIdentity::source).sorted()}",
        )
    }
    descriptors.groupBy(DescriptorIdentity::symbol).filterValues { it.size > 1 }.forEach { (symbol, duplicates) ->
        throw GradleException(
            "Duplicate $label descriptor symbol '$symbol': ${duplicates.map(DescriptorIdentity::source).sorted()}",
        )
    }
}

private fun featureModuleDescriptor(file: File): EntryFeatureModuleDescriptor {
    val properties = file.descriptorProperties(FEATURE_KEYS)
    return EntryFeatureModuleDescriptor(
        id = properties.required("id", file),
        moduleSymbol = properties.required("module", file),
        source = file.invariantSeparatorsPath,
    )
}

private fun typeModuleDescriptor(file: File): EntryTypeModuleDescriptor {
    val properties = file.descriptorProperties(TYPE_KEYS)
    return EntryTypeModuleDescriptor(
        id = properties.required("id", file),
        factorySymbol = properties.required("factory", file),
        source = file.invariantSeparatorsPath,
    )
}

private fun File.descriptorProperties(allowedKeys: Set<String>): Properties {
    val properties = Properties().also { inputStream().use(it::load) }
    val unknownKeys = properties.stringPropertyNames() - allowedKeys
    if (unknownKeys.isNotEmpty()) {
        throw GradleException("Unknown descriptor keys in $invariantSeparatorsPath: ${unknownKeys.sorted()}")
    }
    return properties
}

private fun Properties.required(key: String, file: File): String {
    return getProperty(key)?.trim()?.takeIf(String::isNotEmpty)
        ?: throw GradleException("Missing '$key' in ${file.invariantSeparatorsPath}")
}

private val FEATURE_KEYS = setOf("id", "module")
private val TYPE_KEYS = setOf("id", "factory")
private val MODULE_ID = Regex("""[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*""")
private val QUALIFIED_SYMBOL = Regex("""[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)+""")
