package mihon.entry.interactions.documentation.rendering

import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.shouldBe
import mihon.entry.interactions.documentation.source.EntrySourceSdkConsumerCoveragePlan
import mihon.entry.interactions.documentation.source.EntrySourceSdkContextConsumer
import mihon.feature.graph.ContextInputId
import mihon.feature.graph.ContributionOwner
import mihon.feature.graph.FeatureId
import mihon.feature.graph.FeatureIntegrationId
import org.junit.jupiter.api.Test

class EntrySourceSdkConsumerCoverageMarkdownRendererTest {
    @Test
    fun `renders exact discovered contextual consumer identity`() {
        val plan = plan()

        renderEntrySourceSdkConsumerCoverageMarkdown(plan) shouldBe
            """
            <!-- Generated by ./gradlew generateSourceSdkConsumerCoverage. Do not edit this region. -->

            | SDK contract | Feature | Contextual integration | Evidence input |
            | --- | --- | --- | --- |
            | `FutureSourceContract` | `future.feature` | `future.feature.context` | `future.source.support` |
            """.trimIndent()
    }

    @Test
    fun `requires contextual contracts to remain in handwritten SDK documentation`() {
        val document = """
            Handwritten `OtherContract` documentation.

            $ENTRY_SOURCE_SDK_COVERAGE_START_MARKER

            Generated `FutureSourceContract` row.

            $ENTRY_SOURCE_SDK_COVERAGE_END_MARKER
        """.trimIndent()

        undocumentedEntrySourceSdkContracts(document, plan()) shouldContainExactly
            listOf("FutureSourceContract")
    }

    @Test
    fun `replaces only source coverage markers`() {
        val document = """
            Handwritten `FutureSourceContract` documentation.
            $ENTRY_SOURCE_SDK_COVERAGE_START_MARKER
            Old
            $ENTRY_SOURCE_SDK_COVERAGE_END_MARKER
            After
        """.trimIndent()

        replaceEntrySourceSdkConsumerCoverageGeneratedRegion(document, "New") shouldBe
            """
            Handwritten `FutureSourceContract` documentation.
            $ENTRY_SOURCE_SDK_COVERAGE_START_MARKER

            New

            $ENTRY_SOURCE_SDK_COVERAGE_END_MARKER
            After
            """.trimIndent()
    }

    private fun plan() = EntrySourceSdkConsumerCoveragePlan(
        consumers = listOf(
            EntrySourceSdkContextConsumer(
                contract = FutureSourceContract::class,
                feature = FeatureId("future.feature"),
                featureOwner = ContributionOwner("future.feature"),
                integration = FeatureIntegrationId("future.feature.context"),
                contextInput = ContextInputId("future.source.support"),
            ),
        ),
        exclusions = emptyList(),
        issues = emptyList(),
    )

    private interface FutureSourceContract
}
