package mihon.entry.interactions.documentation.rendering

import io.kotest.assertions.throwables.shouldThrow
import io.kotest.matchers.shouldBe
import mihon.entry.interactions.documentation.EntryContentTypeReferenceNote
import mihon.entry.interactions.documentation.EntryContentTypeReferenceRow
import mihon.entry.interactions.documentation.EntryContentTypeReferenceSection
import mihon.entry.interactions.documentation.EntryContentTypeReferenceStatus
import mihon.entry.interactions.documentation.projection.EntryContentTypeReferenceIssue
import mihon.entry.interactions.documentation.projection.EntryContentTypeReferencePlan
import mihon.entry.interactions.documentation.projection.EntryContentTypeReferencePlannedNote
import mihon.entry.interactions.documentation.projection.EntryContentTypeReferencePlannedRow
import mihon.feature.graph.ContentTypeId
import mihon.feature.graph.ContributionOwner
import org.junit.jupiter.api.Test

class EntryContentTypeReferenceMarkdownRendererTest {
    @Test
    fun `renders discovered types rows statuses and notes deterministically`() {
        val future = ContentTypeId("future-media")
        val alpha = ContentTypeId("alpha")
        val row = EntryContentTypeReferenceRow(
            id = "future-capability",
            section = EntryContentTypeReferenceSection.ENTRY_INTERACTIONS,
            label = "Future | capability",
            order = 100,
        )
        val note = EntryContentTypeReferenceNote(
            id = "derived-note",
            section = EntryContentTypeReferenceSection.ENTRY_INTERACTIONS,
            text = "Derived behavior follows automatically.",
            order = 200,
        )
        val plan = EntryContentTypeReferencePlan(
            contentTypes = listOf(future, alpha),
            rows = listOf(
                EntryContentTypeReferencePlannedRow(
                    definition = row,
                    statuses = mapOf(future to EntryContentTypeReferenceStatus.SOURCE_DEPENDENT),
                ),
            ),
            notes = listOf(EntryContentTypeReferencePlannedNote(note, setOf(future))),
            issues = emptyList(),
        )

        renderEntryContentTypeReferenceMarkdown(plan) shouldBe
            """
            <!-- Generated by ./gradlew generateContentTypeReference. Do not edit this region. -->

            ## Entry interactions

            | Capability | Alpha | Future Media |
            | --- | :---: | :---: |
            | Future \| capability | — | ◇ |

            ::: info

            Derived behavior follows automatically.

            :::
            """.trimIndent()
    }

    @Test
    fun `rejects incomplete plans`() {
        val plan = EntryContentTypeReferencePlan(
            contentTypes = emptyList(),
            rows = emptyList(),
            notes = emptyList(),
            issues = listOf(
                EntryContentTypeReferenceIssue(
                    responsibleOwner = ContributionOwner("future.owner"),
                    subject = null,
                    details = "Missing projection",
                ),
            ),
        )

        shouldThrow<IllegalArgumentException> {
            renderEntryContentTypeReferenceMarkdown(plan)
        }.message shouldBe
            "Cannot render an incomplete content-type reference plan:\n- future.owner: Missing projection"
    }

    @Test
    fun `replaces only the marked region`() {
        val document = """
            Before
            $ENTRY_CONTENT_TYPE_REFERENCE_START_MARKER

            Old generated content

            $ENTRY_CONTENT_TYPE_REFERENCE_END_MARKER
            After
        """.trimIndent()

        replaceEntryContentTypeReferenceGeneratedRegion(document, "New generated content") shouldBe
            """
            Before
            $ENTRY_CONTENT_TYPE_REFERENCE_START_MARKER

            New generated content

            $ENTRY_CONTENT_TYPE_REFERENCE_END_MARKER
            After
            """.trimIndent()
    }

    @Test
    fun `requires exactly one ordered marker pair`() {
        shouldThrow<IllegalArgumentException> {
            replaceEntryContentTypeReferenceGeneratedRegion("No markers", "Generated")
        }
        shouldThrow<IllegalArgumentException> {
            replaceEntryContentTypeReferenceGeneratedRegion(
                "$ENTRY_CONTENT_TYPE_REFERENCE_END_MARKER\n$ENTRY_CONTENT_TYPE_REFERENCE_START_MARKER",
                "Generated",
            )
        }
        shouldThrow<IllegalArgumentException> {
            replaceEntryContentTypeReferenceGeneratedRegion(
                "$ENTRY_CONTENT_TYPE_REFERENCE_START_MARKER\n" +
                    "$ENTRY_CONTENT_TYPE_REFERENCE_START_MARKER\n" +
                    ENTRY_CONTENT_TYPE_REFERENCE_END_MARKER,
                "Generated",
            )
        }
    }
}
